language: node_js
node_js: stable

# S: Build Lifecycle
install:
  - npm install
  - npm install hexo-generator-searchdb --save

#before_script:

script:
  - hexo clean && hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "Deeeeeeeee"
  - git config user.email "seal.de@foxmail.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GIT_HUB_TOKEN}@${GH_REF}" master:master
# E: Build LifeCycle

branchs:
  only:
    - dev

env:
  global:
    - GH_REF: github.com/Deeeeeeeee/deeeeeeeee.github.io.git
